version: "3.8"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: medios-nginx
    ports:
      - "8087:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./edimedios:/var/www/html:ro
    depends_on:
      - php
    environment:
      - VIRTUAL_HOST=medios.void.cl
    restart: unless-stopped

  php:
    image: php:8.2-fpm-alpine
    container_name: medios-php
    volumes:
      - ./edimedios:/var/www/html
    environment:
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=128
    restart: unless-stopped
    # Instalar extensiones necesarias
    command: >
      sh -c "
        apk add --no-cache $PHPIZE_DEPS libpng-dev libjpeg-turbo-dev freetype-dev &&
        docker-php-ext-configure gd --with-freetype --with-jpeg &&
        docker-php-ext-install -j$(nproc) gd &&
        php-fpm
      "

  # Opcional: Redis para cache
  redis:
    image: redis:7-alpine
    container_name: medios-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
